---
- name: "Configuracao Arch Linux"
  hosts: localhost
  connection: local
  tasks:
    - name: Clone Paru helper
      ansible.builtin.git:
        repo: https://aur.archlinux.org/paru.git
        dest: /tmp/paru

    - name: Compila Paru
      command: chdir=/tmp/paru makepkg -si --noconfirm

    - name: Instala programas e pacotes necessarios
      command: paru -S --noconfirm {{ item }}
      with_items:
        - code
        - postman
        - docker
