---
- name: "Configuracao Arch Linux"
  hosts: localhost
  connection: local
  tasks:
    - name: Clone Paru helper
      ansible.builtin.git:
        repo: https://aur.archlinux.org/paru.git
        dest: /tmp/paru

    - name: Compila Paru
      command: chdir=/tmp/paru makepkg -si --noconfirm
    
    - name: Cria diretorio ssh
      file:
        path: "{{ item.dir }}"
        state: directory
      with_items:
        - dir: "~/.ssh/"

    - name: Gera uma chave ssh
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa

    - name: Instala programas e pacotes necessarios
      command: paru -S --noconfirm {{ item }}
      with_items:
        - code
        - postman
        - docker
        - kwin-bismuth
        - kvantum-qt5
        - openssh
